version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - flix_network
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    networks:
      - flix_network
    depends_on:
      - backend

  database:
    image: duckdb/duckdb:latest
    volumes:
      - ./data:/data
    networks:
      - flix_network
    environment:
      - DUCKDB_DB=/data/movies.db

networks:
  flix_network:
    driver: bridge
