version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_PATH=/data/movies.db
    volumes:
      - ./data:/data
    networks:
      - flix_network
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - flix_network
    restart: unless-stopped

  database:
    image: duckdb/duckdb:latest
    volumes:
      - ./data:/data
    networks:
      - flix_network
    restart: unless-stopped

networks:
  flix_network:
    driver: bridge

volumes:
  data:
